# APPEARANCE
include              ./everforest.conf
background_opacity   0.85
background_blur      1
cursor_trail         1

# TABS
tab_bar_style       powerline
tab_powerline_style angled

# WINDOW
linux_display_server     x11
resize_in_steps          yes
window_padding_width     0 2
confirm_os_window_close -2
placement_strategy       top
enabled_layouts          tall,horizontal,grid

map ctrl+shift+t     new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
